### ISSUE TITLE
opencv_matlab not compiling, Windows 7 x64

### ISSUE THREAD

**Issue by skogsharald** [Itseez/opencv_contrib#634]
opencv_matlab fails to compile using the 3.1.0 releases of both opencv and contrib repositories. I'm using Visual Studio 2012 Express, Visual Studio 11 x64 as my compiler, and matlab_r2016a.

The error triggered is:
`error : ld returned 1 exit statusC:\opencv-3.1.0\modules\matlab\collect2.exe opencv_matlab`

Further up in the log is the following:
```
48>  CMake Error at C:/Users/Sajjon/Downloads/opencv_contrib-3.1.0/modules/matlab/compile.cmake:47 (message):
48>    Failed to compile absdiff:
48>    C:\Users\Sajjon\AppData\Local\Temp\mex_43808180884345_4208\absdiff.obj:absdiff.cpp:(.text+0xc36):
48>    undefined reference to 'cv::Mat::create(int, int const*, int)'
48>  
48>    
48>    C:\Users\Sajjon\AppData\Local\Temp\mex_43808180884345_4208\absdiff.obj:absdiff.cpp:(.text+0xe33):
48>    undefined reference to 'cv::Mat::create(int, int const*, int)'
```

Followed by many more `undefined reference`-errors.

I use cmake-gui with cmake 2.8.11.2, which shows
```
  Matlab:
    mex:                         D:/Matlab/bin/mex.bat
    Compiler/generator:          Working
```
Everything is working fine when compiling without opencv_matlab.

Please advice

**Comment by skogsharald** [comment]
@alalek which issue is this a duplicate of? I couldn't find anything that resembled this problem.

**Comment by alalek** [comment]
OK, lets keep this open. There are some issues about Matlab build/bindings, but this case is different and possible looks like to support new version of Matlab (do you have issues with Matlab 2014?).

I hope community may help somehow. Also you can ask support on http://answers.opencv.org

**Comment by skogsharald** [comment]
That seems to have done the trick. No errors with Matlab 2014a.
Thank you.

**Comment by brentsony** [comment]
Error with Matlab 2016b:

Linking CXX executable ../../bin/opencv_test_stitching
[ 89%] Built target opencv_test_stitching
[ 89%] Generating Matlab source files
[ 89%] Built target opencv_matlab_sources
[ 89%] Compiling Matlab source files. This could take a while...
CMake Error at /opt/dev/lib/opencv_contrib/modules/matlab/compile.cmake:47 (message):
  Failed to compile estimateAffinePartial2D:
  /opt/dev/lib/opencv/build/modules/matlab/src/estimateAffinePartial2D.cpp:
  In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:

  /opt/dev/lib/opencv/build/modules/matlab/src/estimateAffinePartial2D.cpp:47:67:
  error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::bridge::Bridge>
  >::value_type’ has no member named ‘toSizeT’

     size_t maxIters = inputs[4].empty() ? (size_t) 2000 : inputs[4].toSizeT();
                                                                     ^
