### ISSUE TITLE
mapperpyramid.cpp does not compile with opencv 2.4.9 

### ISSUE THREAD

**Issue by SteffF** [Itseez/opencv_contrib#26]
Hi,
if i compile the library with visual c++ 2010, i got these message:

  mapperpyramid.cpp
..\..\..\contrib\modules\reg\src\mapperpyramid.cpp(93): error C2039: 'get': Ist kein Element von 'cv::Ptr<_Tp>'
          with
          [
             _Tp=cv::reg::Map
         ]

Thank you,
Steff

**Comment by StevenPuttemans** [comment]
Hmm you are trying to mix the contrib module with OpenCV2.4.9 which is not possible. It only works with OpenCV3.0 and higher. There was no seperate module before OpenCV3.0. @mshabunin this can be closed (running through PRs to clean them up a bit)

**Comment by StevenPuttemans** [comment]
@alalek should I address you instead for all the others I am checking?

**Comment by alalek** [comment]
@StevenPuttemans no, mention is not required. OpenCV team usually receives all notifications.

**Comment by StevenPuttemans** [comment]
Okay thank you!
